export const allCountries = {
  "sa": "Saudi Arabia",
  "ae": "United Arab Emirates",
  "qa": "Qatar",
  "kw": "Kuwait",
  "bh":"Bahrain",
  "om":"Oman",
  "ye":"Yemen",
  "iq": "Iraq",
  "sy": "Syria",
  "lb": "Lebanon",
  "jo":"Jordan",
  "ps":"Palestine",
  "eg": "Egypt",
  "ma": "Morocco",
  "ly": "Lybia",
  "tn": "Tunisia",
  "dz": "Algeria",
  "sd":"Sudan",
  "ss":"South Sudan",
  "so" : "Somalia",
  "dj":"Djibouti",
  "mr":"Mauritani",
  "km":"Comoros",
  "il": "Israel",
  "ir": "Iran",
  "tr": "Turkey",
  "cy": "Cyprus",
  "it": "Italy",
  "gr": "Greece",
  "fr": "France",
  "de": "Germany",
  "be": "Belgium",
  "nl":"Holland",
  "at": "Austria",
  "ch": "Switzerland",
  "gb": "United Kingdom",
  "ie": "Ireland",
  "es": "Spain",
  "pt": "Portugal",
  "ru": "Russia",
  "ua": "Ukraine",
  "dk": "Denmark",
  "no": "Norway",
  "se": "Sweden",
  "fi": "Finland",
  "pl": "Poland",
  "rs": "Serbia",
  "ba": "Bosnia and Herzegovina",
  "hr": "Croatia",
  "cz": "Czechia",
  "lu": "Luxembourg",
  "mc":"Monaco",
  "us": "United States",
  "ca": "Canada",
  "au": "Australia",
  "nz":"New Zealand",
  "by":"Belarus",
  "ge":"Georgia",
  "bg": "Bulgaria",
  "hu": "Hungary",
  "ro":"Romania",
  "am":"Armenia",
  "sk":"Slovakia",
  "si":"Slovenia",
  "md":"Moldova",
  "is":"Iceland",
  "ee":"Estonia",
  "lv":"Latvia",
  "al":"Albania",
  "mt": "Malta",
  "kz": "Kazakhstan",
  "az":"Azerbaijan",
  "cn": "China",
  "jp": "Japan",
  "hk": "Hong Kong",
  "sg": "Singapore",
  "in": "India",
  "pk": "Pakistan",
  "id": "Indonesia",
  "th": "Thailand",
  "my":"Malaysia",
  "bd": "Bangladesh",
  "ph": "Philippines",
  "vn": "Vietnam",
  "kr": "South Korea",
  "kp":"North Korea",
  "af":"Afghanistan",
  "uz":"Uzbekistan",
  "tw":"Taiwan",
  "tm":"Turkmanistan",
  "mv":"Maldives",
  "ar": "Argentina",
  "br": "Brazil",
  "mx": "Mexico",
  "uy":"Uruguay",
  "py":"Paraguay",
  "pe":"Peru",
  "ve": "Venezuela",
  "cl":"Chile",
  "co":"Colombia",
  "ec":"Ecuador",
  "cu":"Cuba",
  "cr":"Costa Rica",
  "pa": "Panama",  
  "ht":"Haiti",
  "hi":"Hawaii",
  "za": "South Africa",
  "sn":"Senegal",
  "cm":"Cameroon",
  "ci":"Ivory Coast",
  "ng":"Nigeria",
  "et":"Ethiopia",
  "ke":"Kenya",
  "gh":"Ghana",
  "er":"Eritrea",
  "ne":"Niger",
  "zm":"Zambia",
  "td":"Chad",
  "gn":"Guinea",
  "cg":"Congo",
  "tz":"Tanzania",
  "ug":"Uganda",
  "mz":"Mozambique",
  "bf":"Burkina Faso",
  "mw":"Malawi",
};